name: Terraform CI/CD

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:
jobs:
  resourcegroups:
    runs-on: ubuntu-latest

    name: 'deployments'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIEND_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      WORKING_DIR: ./isakn-oppg2/deployments
      
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Terraform Init
      id: init
      run: terraform init
      working-directory: ${{ env.WORKING_DIR }}
      
    - name: Terraform Plan
      run: terraform plan -var-file=../isakn-oppg2/deployments/terraform.tfvars.dev
      working-directory: ${{ env.WORKING_DIR }}
