name: Destroy stack

on:
  workflow_dispatch:

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIEND_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  WORKING_DIR: ./isakn-oppg2/deployments

jobs:
  Destroy_stack:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Terraform Init
      id: init
      run: terraform init
      working-directory: ${{ env.WORKING_DIR }}

    - name: Terraform workspace select or create
      run: terraform workspace select dev || terraform workspace new dev
      working-directory: ${{ env.WORKING_DIR }}

    - name: Terraform Destroy dev
      run: terraform destroy -auto-approve -var-file="terraform.tfvars.dev"
      working-directory: ${{ env.WORKING_DIR }}
