name: TFSEC

on:
  workflow_run:
    workflows: ["Validate"]
    types:
        - completed
  workflow_dispatch:

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIEND_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  WORKING_DIR: ./isakn-oppg2/deployments

jobs:
  TFSEC:
    name: 'Security Check'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: tfsec
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
            working-directory: ${{ env.WORKING_DIR }}
            github_token: ${{env.GITHUB_TOKEN}}
            soft_fail: true