name: Validate

on:
  push:
    branches-ignore:
        - 'main'

  workflow_dispatch:

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIEND_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  WORKING_DIR: ./isakn-oppg2/deployments

jobs:
  Validate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Terraform Init
      id: init
      run: terraform init
      working-directory: ${{ env.WORKING_DIR }}

    - name: Terraform workspace select or create
      run: terraform workspace select staging || terraform workspace new staging
      working-directory: ${{ env.WORKING_DIR }}

    - name: Terraform Validate staging
      run: terraform validate
      working-directory: ${{ env.WORKING_DIR }}